### ISSUE TITLE
Remote mode : Problem with OnFilter change and OnPageChange

### ISSUE THREAD

**Issue by remy-poirier** [AllenFang/react-bootstrap-table#1187]
Hello,

I will try to be as clear as possible.

I use your library with the remote mode, I basically do filtering, sortering, and pagination. 
I recently implemented the filter by column, and implemented the onFilterChange.

It works pretty well if all I do is filtering, but when I try to change the page with this filter, my handler to change page is called, and the data is refreshed, so that's ok for this, it's the good data that is displayed, but the problem is that the page highlighted is still the page 1 whereas the value of the currentPage in the state is 2 and this is this value that is passed to the `page` parameter of my `options` object that I pass to my Table.

Do you have any idea ?

**Comment by AllenFang** [comment]
@remy-poirier, could you have a simple and minimal for me to reproduce this issue? thanks 👍

**Comment by AllenFang** [comment]
BTW, is that same condition with https://github.com/AllenFang/react-bootstrap-table/issues/1037 ?

**Comment by AllenFang** [comment]
Fixed on `v3.1.8`

**Comment by BenoitAverty** [comment]
I still have this problem in version 3.2.0. I thinks it's linked to the #1037 issue yes.

What I observed is this : When a filter is active, and the page is changed, it fires the `onFilterChange` callback. This makes the `state.currPage` reset to 1 (as discussed in #1037) even though the `props.options.page` does not change. This causes a mismatch between `props.options.page` and `state.currPage`.

It boils down to the same think I said in issue #1037 : when the table is in remote mode, the `state.currPage` should **always** be equal to` options.page`.

I know you don't agree, so as a workaround I made the page in my component be restet to one when filter changes. But in that case, I can't do it : that would make the page impossible to change when a filter is active !

This doesn't seem to happen for text filters, because the filterchange is not called when the page changes.

**Comment by BenoitAverty** [comment]
@remy-poirier Can you tell us if you still have the issue with the latest version ?

**Comment by BenoitAverty** [comment]
One solution would be to change the condition at https://github.com/AllenFang/react-bootstrap-table/blob/master/src/filters/Select.js#L27 so that the filter is not fired when changing the options object. By making a deep comparison instead of object comparison this would not fire the event unless necessary

**Comment by AllenFang** [comment]
@BenoitAverty, this is is not related with #1037

For your PR, is for https://github.com/AllenFang/react-bootstrap-table/issues/1174 also?

Thanks 👍

**Comment by BenoitAverty** [comment]
It is related to #1037 because fixing #1037 would also fix this issue (for my case, there can be several variants of this issue).

But fixing this one would not necessarily fix the other, I agree.

**Comment by rrameshkumar76** [comment]
This fixes the filter issue(Maximum call stack size exceeded) we had on remote table. Thanks a lot.

**Comment by theGirrafish** [comment]
Glad I'm not the only one, I seem to be having this problem also https://github.com/AllenFang/react-bootstrap-table/issues/1449.
Is there any fix for this after all?

**Comment by 9005** [comment]
@AllenFang : I installed 3.1.8. Its still same issue. page Number resets to 1 when i apply text filter in remote mode

**Comment by 9005** [comment]
@AllenFang : I think this is very serious bug. In current situation with react-bootstrap-table it is not possible to use text filter with remote mode along with pagination. Somehow i converted text filter to select filter and make sure their is no bug.This issue is only for text filters whereas select filter works perfectly fine. But Allen I think this issue needs to be resolved. Your comment on this!!
