### ISSUE TITLE
3 React warnings 

### ISSUE THREAD

**Issue by carlosgg93** [AllenFang/react-bootstrap-table#1519]
These 3 warnings appears when I stay in dev enviroment:

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

`render() {
        const state = this.props.state;`

        const selectRowAlarms = {
            mode: 'radio',
            clickToSelect: true,
            onSelect: this.onAlarmsRowSelect,
            bgColor: '#FDFD96',
            hideSelectColumn: true
        };

        const selectRowMeasures = {
            mode: 'radio',
            clickToSelect: true,
            onSelect: this.onMeasuresRowSelect,
            bgColor: '#FDFD96',
            hideSelectColumn: true
        };
        return (<BootstrapTable data={channelsDVBT} maxHeight={200} scrollTop={ 'Bottom' } selectRow={ selectRowMeasures } striped hover>
                            <TableHeaderColumn isKey dataField='id'>Channel</TableHeaderColumn>
                            {labels.map((label, i) => {
                                return <TableHeaderColumn key={i} dataField={label.id}>{label.label}</TableHeaderColumn>
                            })}</BootstrapTable>
        );
    }`

**Comment by AllenFang** [comment]
Thanks @carlosgg93, I'll checkout this out and for the `PropTypes` issue, it was fixed on `v4.0.0-beta.9`

**Comment by AllenFang** [comment]
@carlosgg93 , for the first warning, I think `react-bootstrap-table` dont use `createClass` directly, so in your mention above, what dev enviroment you used? your dev is means the `react-bootstrap-table`'s?

**Comment by wallena3** [comment]
Sorry for bother. I upgrade to v4.0.0-beta.9  but the PropTypes warning still exist.  There is no 'React.PropTypes ' in my code. So what's wrong or what can I do? Thanks!

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead.

**Comment by AllenFang** [comment]
@wallena3 how did you upgrade to `v4.0.0-beta.9`?  I saw the `v3.5.0` in your `package.json`?!

**Comment by AllenFang** [comment]
BTW, could you please post the warning message here, thanks you~

**Comment by viktorko99** [comment]
@wallena3 
You have warning because of using 
```
import React, { PropTypes } from 'react';
```

You should install prop-types package via npm.
In console type 

```
npm install --save prop-types
```

and I code implemt it like 

```
import PropTypes from 'prop-types';
```

**Comment by wallena3** [comment]
Alright guys, It's my fault,I simple run npm install --save react-bootstrap-table  
 I thought that 3.5.0 is the same as 4.0.0beta9.    
And who can tell me what's the meaning of  "Bump to v3.5.0"? Many thanks!
```
v4.0.0-beta.9
@AllenFang AllenFang released this 22 hours ago
Bump to v3.5.0
```

**Comment by AllenFang** [comment]
@wallena3 `v3.5.0` still use `PropTypes` from `react`, I will upgrade to `v4.0.0` as official release in this weekend,

**Comment by AllenFang** [comment]
`v4.0.0` released ✌️
