### ISSUE TITLE
"selectRow" checkbox of first selected row doesn't get checked on Firefox (44.0.2) ...

### ISSUE THREAD

**Issue by shyblower** [AllenFang/react-bootstrap-table#314]
... when clickToSelect is true and you don't click directly on the checkbox.
The backgroundcolor correctly changes, though.

**Comment by AllenFang** [comment]
@shyblower, what version did you used? and could you please give me an example? btw, only happened on firefox? Thanks :)

**Comment by shyblower** [comment]
I used react-bootstrap-table1.5.4 on Firefox-44.0.2. To see if it was only a Firefox problem I tried again on the latest Chromium browser where it worked flawlessly :)

Steps to reproduce: 
1. Create a 2 row table with selectRow in "checkbox" mode and clickToSelect set to true in the selectRow properties.
2. Click on one of the rows (not directly on the checkbox).
3. The row becomes correctly coloured with the chosen bgColor but the checkbox will NOT display a check mark.
4. Click somewhere on the second row . Now this row will show the check mark correctly.

It doesn't matter which row you click first, only the first selected row will expose this behaviour.
If you clear the selection and do it again it will still behave as described.

**Comment by AllenFang** [comment]
@shyblower, could you try ```v1.6.0``` again for this issues?

**Comment by shyblower** [comment]
Could you please set a v1.6.0 tag as you did with the previous releases, because I my build system downloads a zip file based on the version tag automatically. It would be much easier for me to test it that way.

**Comment by AllenFang** [comment]
sorry, I've pushed v1.6.0 as a tag, check it out!

**Comment by shyblower** [comment]
It still does not work. Maybe a thing to mention is that when I click directly on the checkbox (where it kind of works), the check mark appears only after I have moved the cursor outside the checkbox rectangle. But this happens also only with the first row that I select. The second selection shows the check mark immediately.

**Comment by AllenFang** [comment]
ok, it's strange, could you please give me your example code? or could your reproduce this issue on http://allenfang.github.io/react-bootstrap-table/example.html#select-checkbox?
