### ISSUE TITLE
Sorting with row selection

### ISSUE THREAD

**Issue by jfougere** [AllenFang/react-bootstrap-table#481]
When selecting a row via the checkbox or the click on row (if activated), we loose the current active sort on columns.

It seems to revert to the default sorting.

**Comment by AllenFang** [comment]
@jfougere, ok I'll check this out. Thanks :)

**Comment by AllenFang** [comment]
@jfougere, could you please show your steps for reproducing this issues?  I sort a column and then select a row, but everything is fine.

**Comment by jfougere** [comment]
OK in fact I pinned down the issue to my provided onSelect method.
I do a setState in it and this seems to refresh the table which loose its active sort.

Any ideas ?

**Comment by AllenFang** [comment]
what's state you changed?

**Comment by jfougere** [comment]
I'm setting the state of one property of the datatable's wrapper component.

**Comment by AllenFang** [comment]
I'll test it based on your situation.

**Comment by AllenFang** [comment]
@jfougere, I thinks you need to show your code for me to reproduce this issue. Thanks :)

**Comment by jfougere** [comment]
Ok so I checked and it seems to be related to how i push the data to the table component.

_[Warning] I am a react beginner, so my way of doing thing may be completely wrong ;)_
So my parent component has a method loading data through ajax and store the result in the parent state.
Then the table data attribute is defined like this:
`data={this.state.packages}`

Finally, I have onSelect, onSelectAll methods defined which call setState on the parent component but not changing the loaded data state at all.

I assume that calling setState on the parent, also re-render the table child component. I hoped that setting a property which is not linked to the child component display would not have the child re-rendered. But this does not seems to work like that :).

Maybe you have a suggestion for me.

**Comment by AllenFang** [comment]
@jfougere, ok there's something I need to make sure firstly, 

1. You create a React component which wrap the ```<BootstrapTable>``` directly and also fetch data from server?

2. ```setState``` will call a render for all the child component, if you want some child component do not re-render, you can implement ```shouldComponentUpdate``` to tell react whether re-render it or not.

Hope these can help you :)

BTW, I've wrote a test bese on your case, I also call setState in ```onSelect```, but I dont change the source data, just change a unimportant state. But I didn't see any problem or error.

However, maybe you can tell me your UI flow or scenario, maybe I can help you.

**Comment by jfougere** [comment]
1. yes
2. I was thinking about that, but it would mean that I need to create a child component just to wrap the `<BootstrapTable>` and implement the `shouldComponentUpdate` in it.

I think the difference between my case and yours is just that in your test case the data prop of your table is static and not in the wrapping component state.

I tried an empty setState call and result is the same. So my conclusion is that putting state data as value for the data prop make the `<BootstrapTable>` rerender and so loose active sort.

**Comment by AllenFang** [comment]
2. Exactly

> I think the difference between my case and yours is just that in your test case the data prop of your table is static and not in the wrapping component state.

I'm not sure, need to check my test after my work.

> I tried an empty setState call and result is the same. So my conclusion is that putting state data as value for the data prop make the <BootstrapTable> rerender and so loose active sort.

maybe it's a bug, I'll confirm it today. Thanks !

**Comment by jfougere** [comment]
Ok I think I found where that happens.

In BootstrapTable in method `componentWillReceiveProps `, we have the following code:
```
const sortInfo = this.store.getSortInfo();
const sortField = options.sortName || (sortInfo ? sortInfo.sortField : undefined);
const sortOrder = options.sortOrder || (sortInfo ? sortInfo.order : undefined);
if (sortField && sortOrder) this.store.sort(sortOrder, sortField);
```

The problem here is that default order options have precedence against the one already set in the store.
I think that options.sortName & options.sortOrder should take precedence only if changed otherwise we should keep the one defined in the store if any.

@AllenFang what do u think ?

**Comment by AllenFang** [comment]
@jfougere, I think there's some mistake, could you please use ```defaultSortName``` and ```defaultSortOrder``` instead?

Actually, you find a bug on default sort, because I change the default sort options from ```v2.1.3``` but I forgot to modify the code in ```componentWillReceiveProps```. I'll fix it

**Comment by AllenFang** [comment]
EDIT:
sorry, I make a wrong explantation, that's say, 
```sortName``` and ```sortOrder``` is used on external sorting management, check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/manage-sort-external-table.js)
```defaultSortName``` and ```defaultSortOrder``` is used on default sorting, just work on first rendered.

so I thinks you use ```defaultSortName``` and ```defaultSortOrder``` will solve your problem.

**Comment by jfougere** [comment]
That's it ! Thanks. I was using `sortName` instead of `defaultSortName`. Now my only issue is that sorting result still could change a bit because I can have several lines with same value in some sortable columns. And so the sort result does not seems to be constant in such case.

**Comment by AllenFang** [comment]
@jfougere, any scenario could give me to reproduce this consistency issues?

**Comment by jfougere** [comment]
My scenario is the following:
- one bootstrap table with a few sortable column
- those sortable columns does not contain unique values
- some of the sortable columns have custom sortFunc but not all of them (I don't think it is really relevant here)
- selection of rows activated and a setState call in the onSelect

Results:
When doing the first row selection, the sort is kept now ( thanks @AllenFang to point my mistake), but the sort result is changed a little between rows with same sorted value. 
When doing a second or more row selection, the sort result don't change anymore.

**Comment by jfougere** [comment]
Another thing I just remarked, is that I loose also the current pageSize selection when the table got refreshed after the row is selected.

**Comment by jfougere** [comment]
For the `sizePerPage`, I assume it is in `componentWillReceiveProps` that it get reverted to the one I configured in the options. (I confirm that not adding `sizePerPage` make the current page size selection kept, when the table got rendered again).

For the currPage which is reverted to 1, I did not check yet.

**Comment by AllenFang** [comment]
@jfougere, for the sorting problem, I'll test it. and could you show me your```options``` settings?

**Comment by jfougere** [comment]
Below the table definition:
```
<BootstrapTable ref='datatable' data={this.state.packages}
                                            striped={true} hover={true}
                                            condensed={true} pagination={true} search={true}
                                            multiColumnSearch={true}
                                            searchPlaceholder="Search packages"
                                            exportCSV={true}
                                            csvFileName={this.state.selectValue != null ? this.state.selectValue.value+'.csv' : 'release.csv'}
                                            options={{
                                                    noDataText:'No packages',
                                                    clearSearch: true,
                                                    sizePerPageList: [10, 20, 50, 100],
                                                    sizePerPage: 20,
                                                    defaultSortName: 'name',
                                                    defaultSortOrder:'asc'
                                                    }}
                                            selectRow={{
                                                    mode: "checkbox",
                                                    clickToSelect: true,
                                                    bgColor: "#e7e7e7",
                                                    onSelect: this.onSelect.bind(this),
                                                    onSelectAll: this.onSelectAll.bind(this)
                                            }}>
```

**Comment by AllenFang** [comment]
@jfougere, thanks. I'll check this out

**Comment by AllenFang** [comment]
> For the sizePerPage, I assume it is in componentWillReceiveProps that it get reverted to the one I configured in the options. (I confirm that not adding sizePerPage make the current page size selection kept, when the table got rendered again).
> 
> For the currPage which is reverted to 1, I did not check yet.

@jfougere, sorry, could you show you scenario for this again, I can't reproduce it.

And about the sorting problem, there's a little bug that I'll fix it. But about the same field data sorting, 
there's sill be a little change on it. It's hard to solve it... because the order of the source data has been change every time. In next version, you can try it again

**Comment by jfougere** [comment]
@AllenFang, for the sizePerPage and currPage normally it can be reproduce that way:
- BootstrapTable with option sizePerPage set to a value different from the default one
- BootstrapTable wrapped in a parent component calling setState() so the table is rendered again
- Then when the table is displayed, select a different sizePerPage value than the default / select another page than the first one
- When the table is render again due to the parent setState call you should loose the current sizePerPage selection (which should be back to the sizePerPage option value), and you should be back to page 1

For the sizePerPage for me to me it is due to this line in `componentWillReceiveProps` methods:
````
const sizePerPage = options.sizePerPage || this.state.sizePerPage;
````
If an option has been provided it will overrides the current settings. I think we should check first if the sizePerPage option has been changed in the new props. If yes apply the option, otherwise apply the current settings.

For the currPage it may be linked to the sizePerPage issue since its computed value is linked in my case (no options.page defined).

Thanks for your help!

**Comment by AllenFang** [comment]
@jfougere, ok, I'll review it tomorrow, I'm going to sleep. BTW, you can check the newest version. But there may still a problem in there if the column with same value. I just solve some bug.  I'll describe it in tomorrow.  Thanks 👍

**Comment by jfougere** [comment]
Thanks @AllenFang. Tested with new version. Still same results. (Thanks for #484 )

**Comment by AllenFang** [comment]
@jfougere, the sorting problem is hard to solve, because ```a``` compare to ```b``` is always return 0 if they are the same value. so will cause a little change between desc and asc switching.

**Comment by jfougere** [comment]
@AllenFang I understand no problem. 
The only thing strange is that the order change a little bit only the first time a row gets selected and the table re-rendered. The next times, the order don't change anymore.

So I believe that the source data the first time and the times after are not the same, otherwise the result would be the same.
I'll try to have a look at your code, maybe I can find something to help.

**Comment by AllenFang** [comment]
@jfougere, thanks so much, BTW, I've another question, sorry for my poor english....

> Then when the table is displayed, select a different sizePerPage value than the default / select another page than the first one
I'm not sure what you said, I just know i need to select another sizePerPage value.. but there's no any error or unexpection happened..

anything I miss?

because I cant reproduce it and english is bad. so.. uh, that's why I need a simple demo or repo :)

sorry ;(

**Comment by AllenFang** [comment]
@jfougere, oh I figure out!!

**Comment by AllenFang** [comment]
@jfougere, about the ```currPage``` and ``` sizePerPage``` problems, I've fixed on ```v2.3.5```.

**Comment by jfougere** [comment]
Hi @AllenFang, thanks a lot.

I tested this morning in `v2.3.5`. `sizePerPage` is now fine, but I still have an issue with `currPage`.
Since `v2.3.5`, `currPage` is kept when selecting a row, but not if the selected page is the last one.

Thanks for your help.

**Comment by AllenFang** [comment]
@jfougere, I'll check this out. Thanks your feedback.

**Comment by AllenFang** [comment]
@jfougere, I'm not sure your problem that you encounter after upgrade to ```v2.3.5```. But I found if select a row which is in the last page and then setState will cause jumping to first page.

**Comment by jfougere** [comment]
Yes that's the problem I described! 😀

**Comment by AllenFang** [comment]
@jfougere, great, thanks you :)

**Comment by AllenFang** [comment]
@jfougere, check ```v2.3.6```, sorry for lately fixing

**Comment by jfougere** [comment]
@AllenFang no problem. Thank so much for the fixes. I'll try v2.3.6 today.

About the remaining issue of the sort being change a bit in case of several line with same sorted values. Any news ? 
I was thinking that maybe you could sort first by the sort filter and then by the key. This way the result would always be deterministic regardless of the current array state.

**Comment by jfougere** [comment]
Tested v2.3.6, problem with the last page is gone ! Thank you ;)

**Comment by sebasmagri** [comment]
Hi! I'm getting this behavior on 4.0.2, same setup as above's only without CSV export. Whenever I select a row the sorting status gets reset, the column header does not reflect this change, though. I'm using `defaultSortName` and `defaultSortOrder`. 

In my `onSelect` and `onSelectAll` I set a couple state properties which I use to externally track selected rows. I don't change the `data` at all. However when I disable my custom `onSelect` and `onSelectAll` the sorting does not get reset. I'm trying to implement an approach based on a ref to the table and `selectedRowKeys` in the mean time.

Looking at the code, it seems like `componentWillReceiveProps` always set the store data to a new copy of `data` even if it has not changed. Could this be the source of this behavior and be optimized?

I have a `remote = { search: true }` setting as well that I see could affect this.

I tried using `sortName` and `sortOrder` in `options` as well based on [this part of componentWillReceiveProps](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L277-L278) but the behavior was the same.

**Comment by sebasmagri** [comment]
Just to add that any update to the state will reset the sorting on the table. So I have some additional state linked to modal status in custom buttons in the toolbar and every time those are toggled the sorting status is lost. Hence I think that even if I use the `selectedRowKeys` approach to avoid having custom `onSelect*` I'll still have the same issue.

**Comment by AllenFang** [comment]
Hello @sebasmagri a quick example to reproduce this issue will be good for me, but please keep it simple and minimal, thanks

**Comment by mrijke** [comment]
Hi @AllenFang, I think I'm seeing the same issue, so I've created a small repo to reproduce this issue: https://github.com/mrijke/react-bootstrap-table-repro
What happens is after sorting the table and selecting an element by clicking the row, the `onRowClick` handler does a `setState` call, after which the rows are moving around and the row you clicked might not be under the cursor any more. The interesting part is that this only happens the first time a row is selected, other times after that work fine and the rows are not shuffled any more.

**Comment by AllenFang** [comment]
@mrijke I will spend some time to investigate this issue, thanks

**Comment by AllenFang** [comment]
@sebasmagri sorry for lately reply, your issue has been fixed and @mrijke your issue is some different with @sebasmagri , I'm still checking, thanks

please check on `v4.1.1`
