### ISSUE TITLE
Celledit displaying multiple warnings

### ISSUE THREAD

**Issue by doshisunny** [AllenFang/react-bootstrap-table#613]
When I click on celledit first time I am getting following warnings.
Functionality is working correctly.

warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `toastType` prop on `ToastContainer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. 

warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `id` prop on `ToastContainer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library

warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `toastMessageFactory` prop on `ToastContainer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library.

**Comment by pingwang** [comment]
I am hitting a similar warning:
vendor.bundle.js:25921Warning: You are manually calling a React.PropTypes validation function for the `path` prop on `Route`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details

**Comment by AllenFang** [comment]
I'll check this out, and something duplicated with #590.   Thanks :)

**Comment by AllenFang** [comment]
Fixed on ```v2.4.4```. thanks :)

**Comment by doshisunny** [comment]
Thank you.
This is still happening for me. But I will check and see if this is something because of my custom code changes.

**Comment by AllenFang** [comment]
@doshisunny, could you show you code and what's the version of ```react``` you installed?
