### ISSUE TITLE
Issue with Pagination Shows Total When Table is Empty

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#719]
So it looks like @AllenFang fixed issue #702, however, now we have problems when there is no data in a table like so:

![screen shot 2016-09-20 at 5 23 27 pm](https://cloud.githubusercontent.com/assets/6808172/18691349/b7ca40be-7f58-11e6-8659-368a6e5a0cf0.png)

**Comment by jflayhart** [comment]
Looks as if the offending line is: https://github.com/AllenFang/react-bootstrap-table/blob/master/src/pagination/PaginationList.js#L85

**Comment by AllenFang** [comment]
I'll fix it, thanks this bug report ;)

**Comment by AllenFang** [comment]
Fixed on ```v2.5.4```. Thanks

**Comment by aghreed** [comment]
This is still an issue in `v2.5.7` here if are using the function callback instead of the boolean value for `paginationShowsTotal`.

Seems like the issue is here: https://github.com/AllenFang/react-bootstrap-table/blob/master/src/pagination/PaginationList.js#L95

Essentially when its a boolean, the `to` value is actually returned as `to + 1`. But when its a function, `to` is not getting that +1 bump.

**Comment by AllenFang** [comment]
Forward to #818. Thanks your bug report :)
