### ISSUE TITLE
react-toastr 2.8.2 breaking build

### ISSUE THREAD

**Issue by aliabbas** [AllenFang/react-bootstrap-table#838]
when webpacking my application with react-bootstrap-table, the react-toastr@^2.8.0 dependecy pulls in 2.8.2 as it should but I'm getting the following error

./~/react-bootstrap-table/~/react-toastr/~/react/lib/ReactTransitionEvents.js
Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'

i'm using node 4.3.1, npm 2.15.1

**Comment by sgentile** [comment]
Not sure if related, but I got a reactDOM error with react-toastr using the very new 15.4.0

**Comment by kellyi** [comment]
I encountered this issue, too. I think removing the caret from this line in `package.json` would fix it by pinning it to always use `react-toastr` 2.8.0:

https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L67

**Comment by madeinfree** [comment]
Hi, @aliabbas @sgentile @kellyi I see the related issue from https://github.com/tomchentw/react-toastr/issues/86

**Comment by kellyi** [comment]
It seems like updating React and ReactDOM to 15.4.0 remedied this issue when using v2.5.8 of this library.

**Comment by AllenFang** [comment]
I think just like @kellyi said, I think fix the verion of ```react-toastr``` is a workaround currently.

**Comment by gravitycode** [comment]
Oh no! the damn caret.

**Comment by AllenFang** [comment]
Fixed on ```v2.5.9```, please upgrade, Solve it by fix ```react-toastr``` on ```v2.8.0```

**Comment by mangreen** [comment]
After changed to install react-bootstrap-table@2.5.9, I still encountered this issue.
My react is 0.14.8 and react-dom is 0.14.7

module.js:338
    throw err;
    ^
Error: Cannot find module 'react-dom/lib/getVendorPrefixedEventName'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/julien/Workspace/Punwave/panswer/node_modules/react-bootstrap-table/node_modules/react-toastr/node_modules/react/lib/ReactTransitionEvents.js:15:34)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/julien/Workspace/Punwave/panswer/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by vapon** [comment]
Hi, that is true. 
react-bootstrap-table@2.5.9 doesn't resolve the problem.
"Module not found: Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'"

**Comment by gravitycode** [comment]
i finally updated to react 15.4.0. Although I think not in all scenarios this is a viable solution. 
I also had to update react-hot-loader

**Comment by madeinfree** [comment]
I think this problem from React 15.4.0, I try to change react-toastr react-dom version into 15.3.0 and problem be resolve, react-toastr use below
```json
"dependencies": {
  "react-dom": "^0.14.0 || ^15.0.0"
}
```
so it will install react-dom 15.4.0 by itself

**Comment by AllenFang** [comment]
HI everyone, that's my fault, its a invalid fixed. Any solution?

**Comment by vapon** [comment]
That is the example how caret dependencies can ruin the build. My project become invalid after react 15.4.0 was released (https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html)
Which version of the react-bootstrap-table uses react-toastr 2.4.0 ? I might downgrade for now.

**Comment by AllenFang** [comment]
but maybe https://github.com/tomchentw/react-toastr/blob/v2.4.0/package.json#L78 will be a problem.

**Comment by AllenFang** [comment]
How about fork ```react-toastr``` to my repo and link it with git repo url in ```package.json```

**Comment by madeinfree** [comment]
agree! maybe this is the temporary solution to fix this problem, when react-toastr didn't fix this problem.

**Comment by vapon** [comment]
Thank you very much! Will check which solution fits better.

**Comment by kellyi** [comment]
Upgrading the top-level React & React-DOM dependencies to 15.4.0 fixed this issue for me. 

I believe the problem's that React-Toastr's using an undocumented API which was done away with in 15.4.0. The dependency started breaking immediately after React 15.4 was released -- and this was published:

https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html

I think having the latest React installed at the top level will fix it temporarily, although I also think the React-Toastr dependency will fail again whenever the React version's incremented. A long-term fix probably has to involve React-Toastr adjusting how it addresses the React & React-DOM APIs.

**Comment by kellyi** [comment]
@AllenFang I think using a forked version of React-Toastr with the React/React-DOM-dependencies pinned at whatever version you want for this would work, too.

It looks as if this might be the/one of the culprits in React-Toastr: 

https://github.com/AllenFang/react-bootstrap-table/issues/838#issuecomment-262181867

**Comment by AllenFang** [comment]
> I think using a forked version of React-Toastr with the React/React-DOM-dependencies pinned at whatever version you want for this would work, too.

yes, I'll fix it later :)  Thanks all you guys give these feedback :+1:

**Comment by AllenFang** [comment]
hi all, I've released ```v2.5.10```, I think it could fix this issue, please let me know if anything goes wrong. Any feedback is welcome :)  thanks.

**Comment by yschoueri** [comment]
It doesn't work for me with package.json dependency
`"react-bootstrap-table": "2.5.10"`

I get the following error/warning when running npm install
```
`-- react-bootstrap-table@2.5.10
  +-- UNMET PEER DEPENDENCY react@^0.14.0 || <15.4.0
  `-- react-toastr@2.8.2  (git+https://github.com/AllenFang/react-toastr.git#777bb9a700de183bd123e9f6e2845164cd77ed87)
    +-- react-addons-update@15.3.2
    `-- react-dom@15.3.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN react-toastr@2.8.2 requires a peer of react@^0.14.0 || <15.4.0 but none was installed.
```

and this one when starting my server in hot reload
```
ERROR in ./~/react-bootstrap-table/lib/toolbar/ToolBar.js
Module not found: Error: Cannot resolve module 'react-modal' in C:\Users\yschoueri.STW\Documents\Code\bidconf-ui\node_modules\react-bootstrap-table\lib\toolbar
 @ ./~/react-bootstrap-table/lib/toolbar/ToolBar.js 25:18-40

ERROR in ./~/react-toastr/~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in C:\Users\yschoueri.STW\Documents\Code\bidconf-ui\node_modules\react-toastr\node_modules\react-dom
 @ ./~/react-toastr/~/react-dom/index.js 3:17-46
```

**Comment by Shaywei** [comment]
I am getting erros on `npm install`:

```ERROR in ./~/react-bootstrap-table/lib/toolbar/ToolBar.js
Module not found: Error: Cannot resolve module 'react-modal' in /Users/shayweiss/git/.../frontend/node_modules/react-bootstrap-table/lib/toolbar
 @ ./~/react-bootstrap-table/lib/toolbar/ToolBar.js 25:18-40

ERROR in ./~/react-toastr/~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in /Users/shayweiss/git/.../frontend/node_modules/react-toastr/node_modules/react-dom
 @ ./~/react-toastr/~/react-dom/index.js 3:17-46```

Reverting to `2.5.8` solved the problem.

**Comment by qiusli** [comment]
Got the following error building my project, not sure why. Any suggestions?

npm ERR! git clone --template=h:\dash\npm\2\npm-cache\_git-remotes\_templates --mirror https://github.com/AllenFang/reac
t-toastr.git h:\dash\npm\2\npm-cache\_git-remotes\git-https-github-com-AllenFang-react-toastr-git-72d29d72: Cloning into
 bare repository 'h:\dash\npm\2\npm-cache\_git-remotes\git-https-github-com-AllenFang-react-toastr-git-72d29d72'...
npm ERR! git clone --template=h:\dash\npm\2\npm-cache\_git-remotes\_templates --mirror https://github.com/AllenFang/reac
t-toastr.git h:\dash\npm\2\npm-cache\_git-remotes\git-https-github-com-AllenFang-react-toastr-git-72d29d72:
npm ERR! git clone --template=h:\dash\npm\2\npm-cache\_git-remotes\_templates --mirror https://github.com/AllenFang/reac
t-toastr.git h:\dash\npm\2\npm-cache\_git-remotes\git-https-github-com-AllenFang-react-toastr-git-72d29d72: fatal: Unabl
e to find remote helper for 'https'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\PROGRA~1\\nodejs\\63847A~1.1\\node.exe" "c:\\PROGRA~1\\nodejs\\63847A~1.1\\node_modules\\npm\\bin\\np
m-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=h:\dash\npm\2\npm-cache\_git-remotes\_templates --m
irror https://github.com/AllenFang/react-toastr.git h:\dash\npm\2\npm-cache\_git-remotes\git-https-github-com-AllenFang-
react-toastr-git-72d29d72
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by sgentile** [comment]
So I have a build that was using "react-bootstrap-table": "^2.5.6",

Now it's started failing on me today..

ERROR in ./~/react-bootstrap-table/lib/toolbar/ToolBar.js
Module not found: Error: Cannot resolve module 'react-modal' in
.../client/node_modules/react-bootstrap-table/lib/toolbar
 @ ./~/react-bootstrap-table/lib/toolbar/ToolBar.js 25:18-40

ERROR in ./~/react-toastr/~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in
.../client/node_modules/react-toastr/node_modules/react-dom
 @ ./~/react-toastr/~/react-dom/index.js 3:17-46

"react": "^15.3.2",
"react-addons-css-transition-group": "^15.3.2",
"react-bootstrap": "^0.30.3",
"react-bootstrap-table": "^2.5.6",
"react-datetime": "^2.6.0",
"react-dom": "^15.3.1",

**Comment by qiusli** [comment]
@sgentile try using 2.5.8. It worked for me.

**Comment by fachhoch** [comment]
I am getting this error
ERROR in ./~/react-bootstrap-table/~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in C:\dev\react-dev\app8\123\react-gs\node_modules\react-bootstrap-table\node_modules\react-dom
 @ ./~/react-bootstrap-table/~/react-dom/index.js 3:17-46


react dependencies 
    "react": "^15.4.0",
    "react-bootstrap-table": "^2.5.8",
    "react-dom": "^15.4.0",
    "react-modal": "^1.5.2",
    "react-toastr": "^2.8.0",


Please advice, I am new bee getting started with react.

**Comment by sgentile** [comment]
I got burned by the caret...

**Comment by sgentile** [comment]
Curious others thoughts - so this change basically broke everyone using ^2.5.x  - which was the default when you run npm install at that time.

Since it was such a breaking item, is it more appropriate to do larger version changes once dependencies change ?

ie. instead of the 2.5.8 that caused the issue, moving to 3.0 ?

**Comment by fachhoch** [comment]
moving to 3.0 fixed the build,  thank you.

**Comment by AllenFang** [comment]
I still figure why have following error
```
ERROR in ./~/react-bootstrap-table/lib/toolbar/ToolBar.js
Module not found: Error: Cannot resolve module 'react-modal' in
.../client/node_modules/react-bootstrap-table/lib/toolbar
 @ ./~/react-bootstrap-table/lib/toolbar/ToolBar.js 25:18-40
```

I'll unpublish ```v2.5.10``` later and I must apologize for this upgrading to everyone.

**Comment by AllenFang** [comment]
v2.5.10 unpublished,  this https://github.com/AllenFang/react-bootstrap-table/pull/854 PR solve some issue about ```react@15.4.x``` and dependency issue.

In next stage, I'll try to figure what's going on for the trouble of ```v2.5.10``` and test next patch more details about forking ```react-toastr``` and narrow down the react version on it.

if there's no any better solution, I'll replace ```react-toastr``` with other package as soon as possible.

Sorry for these accidents with my careless.

**Comment by rahul1059** [comment]
@AllenFang  Can you publish a build with react-toastr fixed 2.8.0.

**Comment by AllenFang** [comment]
@rahul1059, I've do it on ```v2.5.9```, but problem still remain. The root cause is https://github.com/AllenFang/react-bootstrap-table/issues/838#issuecomment-262178484

the problem is the caret on ```react-dom``` and ```react```.

**Comment by rahul1059** [comment]
@AllenFang I followed these steps and it worked: 
- removed caret from react-toastr in package json.
- removed/uninstall react-toastr from node modules.
- run npm install from react-bootstrap-table
- build my project files and its working.
I am using 0.14.8 react/react-dom.

**Comment by AllenFang** [comment]
@rahul1059, what the version of your ```npm```

**Comment by rahul1059** [comment]
2.14.9

**Comment by vapon** [comment]
Guys, I just have performed clean 'npm install' and everything worked fine. And when looked up into node_modules, I discovered that *react-dom*  ver. 15.14.1 was installed (released 7 hours ago (!)).
So seems like *getVendorPrefixedEventName* was reverted. At least I could see it.

**Comment by AllenFang** [comment]
https://github.com/facebook/react/releases/tag/v15.4.1
But I cant figure why.  Any evidence for fixing getVendorPrefixedEventName problem?!

**Comment by AllenFang** [comment]
BTW, https://github.com/AllenFang/react-bootstrap-table/releases/tag/v2.6.0-beta.1

I release ```v2.6.0-beta.1```, anyone can try it?   

```npm install react-bootstrap-table@2.6.0-beta.1```

**Comment by madeinfree** [comment]
OK, I help to try this version and think about any way to resolve this issue now

**Comment by AllenFang** [comment]
@madeinfree, if you have time, you can try 15.4.0 and 15.4.1 both condition. BTW, today, I cant reproduce this issue in my client. I almost blow up today..

**Comment by AllenFang** [comment]
I dont see any error on webpacking, but got following error on page running,
```
invariant.js:38 Uncaught Error: Objects are not valid as a React child (found: Error: id can't be empty value.). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `ToastMessage.animation`.(…)
```
Reproduce steps:
1. enable ```insertRow```
2. click insert button on page
3. dont keyin any data
4. Click save button
5. Above error appear on browser console

**Comment by vapon** [comment]
@AllenFang, you are right *NO* evidence of fixing it within the React's release notes, that's why I was surprised and checked node_modules. I'm just a narrow minded java developer and still thinking that using fixed dependencies in package.json is the best way.

**Comment by rahul1059** [comment]
Its not working react/react-dom 0.14.8. I haven't updated my react.

**Comment by AllenFang** [comment]
@rahul1059, any error message?

**Comment by AllenFang** [comment]
Some feedback

```npm@2``` + ```react-bootstrap-table@2.5.9``` + ```react@15.3.2```
wepbacking fail cause by Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'

```npm@3``` + ```react-bootstrap-table@2.5.9``` + ```react@15.3.2```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@2``` + ```react-bootstrap-table@2.6.0-beta.1``` + ```react@15.3.2```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@3``` + ```react-bootstrap-table@2.6.0-beta.1``` + ```react@15.3.2```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@2``` + ```react-bootstrap-table@2.5.9``` + ```react@15.4.0``` or ```react@15.4.1```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@3``` + ```react-bootstrap-table@2.5.9``` + ```react@15.4.0``` or ```react@15.4.1```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@2``` + ```react-bootstrap-table@2.6.0-beta.1``` + ```react@15.4.0``` or ```react@15.4.1```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

```npm@3``` + ```react-bootstrap-table@2.6.0-beta.1``` + ```react@15.4.0``` or ```react@15.4.1```
wepbacking pass but got  invariant.js:38 Uncaught Error: Objects are not valid as a React child  on runnging

**Comment by AllenFang** [comment]
if someone got the following error after use ```v2.6.0-beta```, 
```
invariant.js:38 Uncaught Error: Objects are not valid as a React child (found: Error: id can't be empty value.). 
If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `ToastMessage.animation`.(…)
```
please tell me

**Comment by rahul1059** [comment]
I am getting same error message. `Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName'`

**Comment by AllenFang** [comment]
Maybe I would like to replace ```react-toastr``` by ```react-s-alert```..., https://github.com/AllenFang/react-bootstrap-table/issues/350

**Comment by AllenFang** [comment]
Fixed on ```v2.6.0```.  you should not see any module resolve issue when webpacking and no any error on running.  This https://github.com/AllenFang/react-bootstrap-table/issues/838#issuecomment-262557072 solved on ```v2.6.0```.

If any trouble or issue is related with ```react-toastr```, please tell me. Thanks.

**Comment by rahul1059** [comment]
I am getting the same error. I installed v2.6.0 and i am using react 0.14.8.

> events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'react-dom/lib/getVendorPrefixedEventName' from 'C:\.....\node_modules\react-bootstrap-table\node_modules\react-toastr\node_modules\react\lib'

**Comment by AllenFang** [comment]
@rahul1059, ok, I''' check this out. could you describe your steps?  I guess you remove ```react-bootstrap-table``` firstly and install it again?

**Comment by rahul1059** [comment]
@AllenFang  I did following steps.

- Removed react-bootstrap-table and installed v2.6.0. 

- Removed node modules and re installed everything with react-bootstrap-table v2.6.0

Both of these throwing same error. 

> Error: Cannot find module 'react-dom/lib/getVendorPrefixedEventName' from 'C:.....\node_modules\react-bootstrap-table\node_modules\react-toastr\node_modules\react\lib'

**Comment by AllenFang** [comment]
@rahul1059, I can reproduce it on ```npm@2``` but not in ```npm@3```. I'm still figure why in ```npm@2``` the ```react-toastr``` which installed with ```react@15.4.1``` instead of ```react@15.3.2```.  The problem still remain even I set perrDependencies like https://github.com/AllenFang/react-toastr/blob/test/react-version/package.json#L90

**Comment by rahul1059** [comment]
@AllenFang  Any update for npm@2?

**Comment by AllenFang** [comment]
Currently, I still figure out why, I know some solution, but no any solution is well. For now, after ```v2.6.0``` only ```react@0.14.x``` with ```npm@2``` still have issues. I'll keep to fix this remain problem. sorry for waiting a long time.

**Comment by jamiguet** [comment]
@AllenFang Are the changes going to be proposed to upstream and integrated into a version?
I have the problem that I build without access to the internet, so I need full releases so that my local repo can download them.

Please advise on toastr releases that integrate the fix you need.

**Comment by olegserov** [comment]
I had similar problem, what I did:
0. removed node_modules
1. installed npm3.
2. upgraded dependencies (see attached f
<img width="1002" alt="screen shot 2016-12-12 at 16 57 35" src="https://cloud.githubusercontent.com/assets/129835/21118491/1f3a0b66-c08c-11e6-8013-b589355bd5f5.png">

ile)
3. looked at npm3 list and found " ERR! peer dep missing" ... react-dom.
4. npm3 install react-dom react-overlays react-prop-types --save-dev
5. Now it builds.

**Comment by AllenFang** [comment]
@jamiguet, is this https://github.com/AllenFang/react-bootstrap-table/issues/861 ? we are solving it. Need some time, a lots of thing need to do. Sorry ;(

**Comment by af-fess** [comment]
I still get the same issue, I use latest version `2.8.2` with dependancies:

```
  "react": "^0.14.7",
    "react-bootstrap": "^0.30.7",
    "react-bootstrap-table": "^2.8.2",
    "react-dom": "~0.14.7",
```
Inside `react-bootstrap-table`:

```
  "dependencies": {
    "classnames": "^2.1.2",
    "@allenfang/react-toastr": "2.8.2"
  },
```

```
Error in compilation in webpack: ModuleNotFoundError: 
Module not found:
 Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName' in /Users/.../client/node_modules/react-bootstrap-table/node_modules/@allenfang/react-toastr/node_modules/react/lib

/Users/.../client/webpack.vendors.config.js:56
                    throw new Error('Error in compilation in webpack: ' + stats.compilation.errors);

```

**Comment by AllenFang** [comment]
@af-fess, what's the version of ```npm``` and could you show me your ```node_modules``` by following command
```bash
npm list --depth=1 | grep react
```

**Comment by af-fess** [comment]
npm - `2.5.18`

```
$ npm list --depth=1 | grep react
├─┬ babel-preset-react@6.16.0
│ ├── babel-plugin-transform-react-display-name@6.8.0
│ ├── babel-plugin-transform-react-jsx@6.8.0
│ ├── babel-plugin-transform-react-jsx-self@6.11.0
│ └── babel-plugin-transform-react-jsx-source@6.9.0
├─┬ react@0.14.8
├─┬ react-bootstrap@0.30.7
│ ├── react-overlays@0.6.10
│ ├── react-prop-types@0.4.0
├─┬ react-bootstrap-table@2.8.2
│ ├── babel-preset-react@6.16.0 extraneous
│ ├── eslint-plugin-react@3.6.3 extraneous
│ ├── react@15.4.1
│ ├── react-bootstrap@0.29.5 extraneous
│ ├── react-dom@15.4.1
│ ├── react-hot-loader@3.0.0-beta.6 extraneous
│ ├── react-router@3.0.0 extraneous
│ ├── react-toastr@2.8.2
├── react-dom@0.14.8
├─┬ react-hot-loader@3.0.0-beta.6
│ ├── react-deep-force-update@2.0.1
│ ├── react-proxy@3.0.0-alpha.1
│ ├── redbox-react@1.3.3
├─┬ react-router@2.8.1
│ ├── hoist-non-react-statics@1.2.0
├─┬ react-split-pane@0.1.57
│ └── react-style-proptype@1.4.0

```

also I tried to reinstall all `node_modules`, got the same error.

---

The problem is solved by updating `react/react-dom` to latest `15.4.1` that a cannot use for today (have a lot of deps)

**Comment by ianks** [comment]
@AllenFang Maybe we should just ditch react-toastr tbh. I don't see this issue being fixed anytime soon and its forcing us to be locked at older versions of React.

**Comment by AllenFang** [comment]
@ianks, yap, that issue still remain until now, actually I had tried the [react-s-alert](https://github.com/juliancwirko/react-s-alert) but it also have the same problem.  Anyway, I'll try it again in recently, maybe I just got something wrong.

**Comment by zekedroid** [comment]
Any updates on this issue?

**Comment by gengjiawen** [comment]
Is it possible we remove this library and related function ?

**Comment by AllenFang** [comment]
I really want to remove it but it will be a big change

**Comment by zekedroid** [comment]
@AllenFang why not revert to a version of react-toaster that ISN'T using a scoped package. Why is the dependency listed with your scope? If it's because you forked and changed the library, maybe just change it to a different name so it doesn't clash? Or release an alpha version. Either way, this seems like it's not an issue with the library, just how it's being installed and depended on. 

I know npm can be a pain, so maybe let us know what you've tried and we may be able to help!

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216

**Comment by AllenFang** [comment]
After `v4.0.0`, `react-bootstrap-table doesn't use `react-toastr` anymore.

**Comment by athenaxing** [comment]
@AllenFang, so when v4.0.0 will be released?
